services:
  - type: web
    name: syphir-api
    env: node
    buildCommand: bun install
    startCommand: bun run server.js
    envVars:
      - key: PORT
        value: 3000
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false